scheb_two_factor:
    google:
        enabled: true
        issuer: "MonApp"
        server_name: "MonApp"
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken